---
- name: Create a postgreSQL DB server
  hosts: all
  remote_user: ubuntu
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    # - install
    - createdb
  handlers:
    - name: restart postgres
      service: name=postgresql state=restarted
