---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Ensure bash, OpenSSl, and libssl are the latest versions
  apt: name={{ item }} update_cache=true state=latest
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc
    - python3-dev
    - python3-pip
    - acl

- name: "Install DB packages"
  apt: "name={{ packages }} state=present"
  vars:
    packages:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - libpcap-dev

- name: "Install Python packages"
  pip: "name={{ item }}  state=present"
  with_items:
    - psycopg2-binary

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes

- name: "find out if PostgreSQL is initialized"
  ansible.builtin.stat:
    path: "/var/lib/pgsql/data/pg_hba.conf"
  register: postgres_data

# - name: "Initialize PostgreSQL"
#   shell: "postgresql-setup initdb"
#   when: not postgres_data.stat.exists

- name: "Start and enable services"
  service: "name={{ item }} state=started enabled=yes"
  with_items:
    - postgresql
